# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Unsolicited Advice
email: jesse.pangburn@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  I'm an ex software architect, who retired at 41.  This site has posts that basically provide unsolicited advice and opinions on things that I'm familiar with.  See the About page for more detail.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jpangburn.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  jpangburn
# show excerpts on post listing
show_excerpts: true
# enable google_analytics
google_analytics: UA-158692727-1
# customize header links
header_pages:
  - about.md
  - privacy.md
# use my custom facebook code
facebook_comments:
  app_id: 818791938587632
  width: 100%
  #numposts: 10

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

